                                        Working with NUMPY Library in Python

Version of Numpy

In [4]:
import numpy as np
np.__version__

'1.13.3'

Original list into a One dimensional Array

In [5]:
lst = [12.23, 13.32, 100, 36.32]
oneDarray = np.array(lst)
oneDarray

array([  12.23,   13.32,  100.  ,   36.32])

3x3 matrix ranging from 2 to 10

In [6]:
n = np.arange(2,11).reshape(3,3)
n

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Null vector with zeros of size 10 and update 6th element to 11

In [9]:
nul = np.zeros(10)
nul[6] = 11
nul

array([  0.,   0.,   0.,   0.,   0.,   0.,  11.,   0.,   0.,   0.])

Array with values ranging from 12 to 38

In [16]:
arry = np.arange(12,38)
arry

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

Reverse an array (first element becomes last)

In [17]:
arry[0],arry[-1] = arry[-1],arry[0]
arry

array([37, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 12])

Array converted to a float type

In [25]:
original = [1, 2, 3, 4] 
x = np.asfarray(original)
type(x)
x

array([ 1.,  2.,  3.,  4.])

Create a 2d array with 1 on the border and 0 inside

In [31]:
ones = np.ones((5,5))
ones[1:-1] = 0
ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.]])

Add a border (filled with 0's) around an existing array

In [38]:
ones_arry = np.ones((3,3))
ones_arry
new_ones = np.pad(ones_arry,pad_width=1,mode="constant",constant_values=0)
new_ones

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Create a 8x8 matrix and fill it with a checkerboard pattern

In [43]:
x=np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Convert a list and tuple into arrays

In [45]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to Array:",np.asarray(my_list))
my_tupule = ([8, 4, 6], [1, 2, 3])
print("Tupule to Array:",np.asarray(my_tupule))

List to Array: [1 2 3 4 5 6 7 8]
Tupule to Array: [[8 4 6]
 [1 2 3]]


Append values to the end of an array

In [52]:
x = [10, 20, 30]
x=np.append(x,[[40,50,60,70,80,90]])
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Create an empty and a full array

In [57]:
x = np.empty((3,4))
print("Empty Array:",x)
y = np.full((3,4),6)
print("Full Array:",y)

Empty Array: [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Full Array: [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


find the real and imaginary parts of an array of complex numbers

In [60]:
x = np.sqrt([1+0j, 0+1j])
print(x.real)
print(x.imag)

[ 1.          0.70710678]
[ 0.          0.70710678]


number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [63]:
x = [5,8,9,6,3,7]
x = np.array(x)
print("size of array:",len(x))
print("Length of one array element in bytes:",x.itemsize)
print("Total bytes consumed by the elements of the array:",x.nbytes)

size of array: 6
Length of one array element in bytes: 4
Total bytes consumed by the elements of the array: 24


Compare each element of array1 and array2 

In [68]:
array_1= np.array([0,10,20,40,60])
array_2 = np.array([0,40])
print(array_1)
print(array_2)
print(np.in1d(array_1, array_2))

[ 0 10 20 40 60]
[ 0 40]
[ True False False  True False]


Common values between two arrays

In [69]:
print(np.intersect1d(array_1,array_2))

[ 0 40]


Unique elements of an array

In [71]:
array_new = np.array([10,20,10,0,80,70,50,20,0,50])
print(np.unique(array_new))

[ 0 10 20 50 70 80]


set difference of two arrays

In [72]:
array_1 = np.array([0,10,20,40,60,80]) 
array_2 = np.array([10,30,40,50,70,90])
print(np.setdiff1d(array_1,array_2))

[ 0 20 60 80]


set exclusive-or of two arrays

In [73]:
print(np.setxor1d(array_1,array_2))

[ 0 20 30 50 60 70 80 90]


union of two arrays

In [75]:
print(np.union1d(array_1,array_2))

[ 0 10 20 30 40 50 60 70 80 90]


construct an array by repeating

In [76]:
print(np.tile(array_1,2))

[ 0 10 20 40 60 80  0 10 20 40 60 80]


repeat elements of an array

In [77]:
print(np.repeat(array_1,2))

[ 0  0 10 10 20 20 40 40 60 60 80 80]


find the indices of the maximum and minimum values along the given axis of an array

In [80]:
print("Maximum:",np.argmax(array_1))
print("Minimum:",np.argmin(array_1))

Maximum: 5
Minimum: 0


sort an along the first, last axis of an array

In [81]:
a = np.array([[4, 6],[2, 1]])
print("Sorting along first axis:",np.sort(a,axis=0))
print("Sorting along last axis:",np.sort(a,axis=1))

Sorting along first axis: [[2 1]
 [4 6]]
Sorting along last axis: [[4 6]
 [1 2]]


Sort pairs of first name and last name return their indices

In [84]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
print(np.lexsort((first_names,last_names)))

[1 3 2 4 0]


Get the values and indices of the elements that are bigger than 10 in a given array

In [88]:
x = array_1[array_1>10]
print(x)
print(np.nonzero(array_1>10))

[20 40 60 80]
(array([2, 3, 4, 5], dtype=int64),)


save a NumPy array to a text file

In [89]:
np.savetxt("NumpyArray.out",array_1,delimiter=",")

create a contiguous flattened array

In [90]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Flattened Array:",np.ravel(x))

Flattened Array: [10 20 30 20 40 50]


Array of size 3*5 with all the elements 2

In [104]:
z = np.full((3,5),2)
z

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

3-D array with ones on the diagonal and zeros elsewhere

In [105]:
g = np.eye(3)
g

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere

In [106]:
y = np.diagflat([4,5,6,8])
y

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

30 evenly spaced elements between 2.5 and 6.5

In [111]:
k = np.linspace(2.5,6.5,30)
k

array([ 2.5       ,  2.63793103,  2.77586207,  2.9137931 ,  3.05172414,
        3.18965517,  3.32758621,  3.46551724,  3.60344828,  3.74137931,
        3.87931034,  4.01724138,  4.15517241,  4.29310345,  4.43103448,
        4.56896552,  4.70689655,  4.84482759,  4.98275862,  5.12068966,
        5.25862069,  5.39655172,  5.53448276,  5.67241379,  5.81034483,
        5.94827586,  6.0862069 ,  6.22413793,  6.36206897,  6.5       ])

1-D array of 20 element spaced evenly on a log scale between 2. and 5.

In [114]:
j = np.logspace(2.,5.,20,endpoint=False)
j

array([   100.        ,    141.25375446,    199.5262315 ,    281.83829313,
          398.10717055,    562.34132519,    794.32823472,   1122.0184543 ,
         1584.89319246,   2238.72113857,   3162.27766017,   4466.83592151,
         6309.5734448 ,   8912.50938134,  12589.25411794,  17782.79410039,
        25118.8643151 ,  35481.33892336,  50118.72336273,  70794.57843841])

Print the following output

In [115]:
p = np.tri(4,3,-1)
p

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]])

3-D Array to 1-D Array

In [117]:
x = np.eye(3)
print(x)
print(np.ravel(x))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[ 1.  0.  0.  0.  1.  0.  0.  0.  1.]


concatenate two 2-dimensional arrays

In [119]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
c = np.concatenate((a, b), 1)
print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


1-D arrays as columns into a 2-D array

In [120]:
a = np.array((10,20,30))
b = np.array((40,50,60))
c = np.column_stack((a, b))
print(c)

[[10 40]
 [20 50]
 [30 60]]


split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order

In [122]:
d = np.arange(1,15)
print(d)
print("After Splitting:",np.split(d,[2,6]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After Splitting: [array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


Get the number of nonzero elements in an array

In [123]:
print(np.count_nonzero(d))

14


create a 5x5 matrix with row values ranging from 0 to 4

In [132]:
t = np.zeros((5,5))
t += np.arange(5)
t

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

create a vector of size 10 with values ranging from 0 to 1, both excluded

In [136]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
x

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

make an array immutable (read-only)

In [139]:
r = np.ones(10)
print(r)
r.flags.writeable = False
r[4] = 1
print(r)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


ValueError: assignment destination is read-only

sum of all the multiples of 3 or 5 below 100

In [155]:
x = np.arange(1, 100)
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
print("Sum of Array",n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum of Array 2318


5x5 cube of 1's

In [ ]:
x = np.ones((5,5,5))
x

create an array of (3, 4) shape, multiply every element value by 3 and display the new array

In [172]:
e = np.arange(12).reshape(3,4)
print("Old array:",e)
e = e*3
print("New array:",e)

Old array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array: [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


Create a function that cubes the elements of the array

In [186]:
def cube_function(array):
    for each in array:
        new_list = []
        n = each*each*each
        new_list.append(n)
    return new_list
h = np.array([2])
cube_function(h)

[8]

NumPy array into Python list

In [191]:
l = np.arange(6).reshape(3,2)
print(l)
print(l.tolist())

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


add an extra column to an numpy array

In [196]:
x = np.array([[10,20,30],[40,50,60]])
y = np.array([[90],[80]])
print(np.append(x,y,axis=1))

[[10 20 30 90]
 [40 50 60 80]]


find unique rows in a numpy array

In [198]:
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])
print(np.unique(x,axis=0))

[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]


replace all elements of numpy array that are greater than specified array(0.5)

In [203]:
b = np.array([[ 0.42436315,0.48558583,0.32924763], 
[ 0.7439979,0.58220701,0.38213418],
[ 0.5097581,0.34528799,0.1563123 ]])
print(b)
b[b>0.5] =0.5
print(b)

[[ 0.42436315  0.48558583  0.32924763]
 [ 0.7439979   0.58220701  0.38213418]
 [ 0.5097581   0.34528799  0.1563123 ]]
[[ 0.42436315  0.48558583  0.32924763]
 [ 0.5         0.5         0.38213418]
 [ 0.5         0.34528799  0.1563123 ]]


remove specific elements in a numpy array

In [204]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]
new_x =np.delete(x,index)
new_x

array([ 20,  30,  60,  70,  80,  90, 100])

remove the negative values in a numpy array

In [211]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
x = x[x>=0]
x

array([0, 2, 3, 4, 5])

Generate five random numbers from the normal distribution

In [212]:
v = np.random.normal(size=5)
v

array([ 0.25883812, -0.33435345, -1.49659659, -1.53245681,  1.96459441])

generate six random integers between 10 and 30

In [216]:
z = np.random.randint(low=10, high=30, size=6)
z

array([27, 10, 24, 10, 24, 21])

create a 3x3x3 array with random values

In [217]:
n = np.random.random((3,3,3))
n

array([[[ 0.73886242,  0.04256758,  0.32532006],
        [ 0.16970166,  0.12212208,  0.81863158],
        [ 0.19004961,  0.64619246,  0.89779937]],

       [[ 0.54173358,  0.27675265,  0.00385821],
        [ 0.48346802,  0.65384114,  0.67821101],
        [ 0.39233905,  0.8500908 ,  0.56624479]],

       [[ 0.69627853,  0.35673363,  0.22245533],
        [ 0.37567109,  0.16180828,  0.34451385],
        [ 0.12976663,  0.32702112,  0.28254109]]])

create a 5x5 array with random values and find the minimum and maximum values

In [222]:
m = np.random.random((5,5))
print(m)
print(m.min())
print(m.max())

[[ 0.65582849  0.12964971  0.06422655  0.22145755  0.77793533]
 [ 0.32593949  0.95078511  0.97568779  0.63820218  0.50385252]
 [ 0.778742    0.25309995  0.00438537  0.40575788  0.35395811]
 [ 0.79376793  0.42399436  0.93665012  0.77089152  0.64553236]
 [ 0.95131804  0.05173477  0.48571121  0.89362633  0.0864523 ]]
0.004385365994
0.975687787509


create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [224]:
u = np.random.random((10,4))
print(u)
f = u[:5]
print(f)

[[ 0.13456571  0.62658852  0.43571866  0.69323661]
 [ 0.14721521  0.27239336  0.71458833  0.78456403]
 [ 0.40631469  0.45897363  0.35908726  0.14288813]
 [ 0.68842905  0.08315403  0.52806526  0.97672761]
 [ 0.38652253  0.44331199  0.95569469  0.25910812]
 [ 0.516383    0.5139593   0.89084732  0.73665844]
 [ 0.84374882  0.09173827  0.62161418  0.12379594]
 [ 0.58070748  0.37579709  0.07649182  0.62808887]
 [ 0.42358167  0.85152633  0.17173106  0.37734668]
 [ 0.62008571  0.60442172  0.69260717  0.47656945]]
[[ 0.13456571  0.62658852  0.43571866  0.69323661]
 [ 0.14721521  0.27239336  0.71458833  0.78456403]
 [ 0.40631469  0.45897363  0.35908726  0.14288813]
 [ 0.68842905  0.08315403  0.52806526  0.97672761]
 [ 0.38652253  0.44331199  0.95569469  0.25910812]]


shuffle numbers between 0 and 10 (inclusive)

In [227]:
i = np.arange(10)
print(i)
np.random.shuffle(i)
print(i)

[0 1 2 3 4 5 6 7 8 9]
[7 1 0 8 6 9 4 5 2 3]


normalize a 3x3 random matrix

In [233]:
p = np.random.random((3,3))
print(p)
xmax= p.max()
xmin = p.min()
print("After Normalization")
x = (x-xmin) / (xmax - xmin)
print(x)

[[  6.69594394e-01   4.82501256e-04   3.90882138e-01]
 [  3.14771651e-01   1.87412499e-01   8.79565392e-01]
 [  4.57404009e-01   9.93158882e-01   2.92258912e-01]]
After Normalization
[  5.03640219e+00   3.02164689e+00   2.01426924e+00  -4.86060981e-04
   4.02902454e+00]


check two random arrays are equal or not

In [242]:
x = np.random.randint(1,10,5)
print(x)
y = np.random.randint(1,10,5)
print(y)
result = np.allclose(x,y)
print(result)

[6 5 2 9 2]
[9 5 3 4 3]
False


 create random vector of size 15 and replace the maximum value by -1

In [246]:
u = np.random.normal(size=15)
print("Before replacing:",u)
print("Maximum:",u.max())
u[u>1]=-1
print("After replacing:",u)

Before replacing: [-1.61396275  0.88658727 -1.83870542 -0.25257271 -0.56723638  1.23255166
 -0.18085912  0.03072198  1.19772276  0.97926317  0.05645149  1.18121509
 -0.18362173 -0.44019234 -0.80245824]
Maximum: 1.2325516636
After replacing: [-1.61396275  0.88658727 -1.83870542 -0.25257271 -0.56723638 -1.
 -0.18085912  0.03072198 -1.          0.97926317  0.05645149 -1.
 -0.18362173 -0.44019234 -0.80245824]


find the most frequent value in an array

In [247]:
s = np.random.randint(0,10,20)
print("Elements in the array:",s)
print("Most Frequent elements in the array:",np.bincount(s).argmax())

Elements in the array: [5 2 4 2 0 6 4 9 5 6 7 1 9 6 2 0 9 8 6 8]
Most Frequent elements in the array: 6


                                        Working with DateTime in NumPy

display all the dates for the month of March, 2017

In [252]:
print("July 2017")
print(np.arange('2017-07','2017-08',dtype='datetime64[D]'))


July 2017
['2017-07-01' '2017-07-02' '2017-07-03' '2017-07-04' '2017-07-05'
 '2017-07-06' '2017-07-07' '2017-07-08' '2017-07-09' '2017-07-10'
 '2017-07-11' '2017-07-12' '2017-07-13' '2017-07-14' '2017-07-15'
 '2017-07-16' '2017-07-17' '2017-07-18' '2017-07-19' '2017-07-20'
 '2017-07-21' '2017-07-22' '2017-07-23' '2017-07-24' '2017-07-25'
 '2017-07-26' '2017-07-27' '2017-07-28' '2017-07-29' '2017-07-30'
 '2017-07-31']


get the dates of yesterday, today and tomorrow

In [255]:
today = np.datetime64('today','D')
print("today:",today)
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print("yesterday:",yesterday)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("tomorrow:",tomorrow)

today: 2017-12-04
yesterday: 2017-12-03
tomorrow: 2017-12-05


count the number of days of a given month

In [258]:
print("Number of days in July 2017")
print(np.datetime64('2017-08-01')-np.datetime64('2017-07-01'))
print("Number of days in July 2018")
print(np.datetime64('2018-08-01')-np.datetime64('2018-07-01'))
print("Number of days in July 2019")
print(np.datetime64('2019-08-01')-np.datetime64('2019-07-01'))

Number of days in July 2017
31 days
Number of days in July 2018
31 days
Number of days in July 2019
31 days


convert numpy datetime64 to Timestamp

In [266]:
from datetime import datetime
print("Current date and time:")
date_time = datetime.utcnow()
print(date_time)

datetime_numpy = np.datetime64(date_time)

print("Time Stamp:")
time_stamp = (datetime_numpy - np.datetime64('1970-01-01T00:00:00Z')) / (np.timedelta64(1,'s'))
print(time_stamp)

Current date and time:
2017-12-04 09:23:18.981972
Time Stamp:
1512379398.98


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  if __name__ == '__main__':
